// <auto-generated />
namespace kck_projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dodany_koszt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodany_koszt));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241650006_dodany_koszt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
